package com.technegames.lexiconda;

import com.technegames.dict.A.DictionaryA1;
import com.technegames.dict.A.DictionaryA2;
import com.technegames.dict.A.DictionaryA3;
import com.technegames.dict.A.DictionaryA4;
import com.technegames.dict.A.DictionaryA5;
import com.technegames.dict.B.DictionaryB1;
import com.technegames.dict.B.DictionaryB2;
import com.technegames.dict.B.DictionaryB3;
import com.technegames.dict.B.DictionaryB4;
import com.technegames.dict.B.DictionaryB5;
import com.technegames.dict.C.DictionaryC1;
import com.technegames.dict.C.DictionaryC2;
import com.technegames.dict.C.DictionaryC3;
import com.technegames.dict.C.DictionaryC4;
import com.technegames.dict.C.DictionaryC5;
import com.technegames.dict.D.DictionaryD1;
import com.technegames.dict.D.DictionaryD2;
import com.technegames.dict.D.DictionaryD3;
import com.technegames.dict.D.DictionaryD4;
import com.technegames.dict.D.DictionaryD5;
import com.technegames.dict.E.DictionaryE1;
import com.technegames.dict.E.DictionaryE2;
import com.technegames.dict.E.DictionaryE3;
import com.technegames.dict.E.DictionaryE4;
import com.technegames.dict.E.DictionaryE5;
import com.technegames.dict.F.DictionaryF1;
import com.technegames.dict.F.DictionaryF2;
import com.technegames.dict.F.DictionaryF3;
import com.technegames.dict.F.DictionaryF4;
import com.technegames.dict.F.DictionaryF5;
import com.technegames.dict.G.DictionaryG1;
import com.technegames.dict.G.DictionaryG2;
import com.technegames.dict.G.DictionaryG3;
import com.technegames.dict.G.DictionaryG4;
import com.technegames.dict.G.DictionaryG5;
import com.technegames.dict.H.DictionaryH1;
import com.technegames.dict.H.DictionaryH2;
import com.technegames.dict.H.DictionaryH3;
import com.technegames.dict.H.DictionaryH4;
import com.technegames.dict.H.DictionaryH5;
import com.technegames.dict.I.DictionaryI1;
import com.technegames.dict.I.DictionaryI2;
import com.technegames.dict.I.DictionaryI3;
import com.technegames.dict.I.DictionaryI4;
import com.technegames.dict.I.DictionaryI5;
import com.technegames.dict.J.DictionaryJ1;
import com.technegames.dict.J.DictionaryJ2;
import com.technegames.dict.J.DictionaryJ3;
import com.technegames.dict.J.DictionaryJ4;
import com.technegames.dict.J.DictionaryJ5;
import com.technegames.dict.K.DictionaryK1;
import com.technegames.dict.K.DictionaryK2;
import com.technegames.dict.K.DictionaryK3;
import com.technegames.dict.K.DictionaryK4;
import com.technegames.dict.K.DictionaryK5;
import com.technegames.dict.L.DictionaryL1;
import com.technegames.dict.L.DictionaryL2;
import com.technegames.dict.L.DictionaryL3;
import com.technegames.dict.L.DictionaryL4;
import com.technegames.dict.L.DictionaryL5;
import com.technegames.dict.M.DictionaryM1;
import com.technegames.dict.M.DictionaryM2;
import com.technegames.dict.M.DictionaryM3;
import com.technegames.dict.M.DictionaryM4;
import com.technegames.dict.M.DictionaryM5;
import com.technegames.dict.N.DictionaryN1;
import com.technegames.dict.N.DictionaryN2;
import com.technegames.dict.N.DictionaryN3;
import com.technegames.dict.N.DictionaryN4;
import com.technegames.dict.N.DictionaryN5;
import com.technegames.dict.O.DictionaryO1;
import com.technegames.dict.O.DictionaryO2;
import com.technegames.dict.O.DictionaryO3;
import com.technegames.dict.O.DictionaryO4;
import com.technegames.dict.O.DictionaryO5;
import com.technegames.dict.P.DictionaryP1;
import com.technegames.dict.P.DictionaryP2;
import com.technegames.dict.P.DictionaryP3;
import com.technegames.dict.P.DictionaryP4;
import com.technegames.dict.P.DictionaryP5;
import com.technegames.dict.Q.DictionaryQ1;
import com.technegames.dict.Q.DictionaryQ5;
import com.technegames.dict.R.DictionaryR1;
import com.technegames.dict.R.DictionaryR2;
import com.technegames.dict.R.DictionaryR3;
import com.technegames.dict.R.DictionaryR4;
import com.technegames.dict.R.DictionaryR5;
import com.technegames.dict.S.DictionaryS1;
import com.technegames.dict.S.DictionaryS2;
import com.technegames.dict.S.DictionaryS3;
import com.technegames.dict.S.DictionaryS4;
import com.technegames.dict.S.DictionaryS5;
import com.technegames.dict.T.DictionaryT1;
import com.technegames.dict.T.DictionaryT2;
import com.technegames.dict.T.DictionaryT3;
import com.technegames.dict.T.DictionaryT4;
import com.technegames.dict.T.DictionaryT5;
import com.technegames.dict.U.DictionaryU1;
import com.technegames.dict.U.DictionaryU2;
import com.technegames.dict.U.DictionaryU3;
import com.technegames.dict.U.DictionaryU4;
import com.technegames.dict.U.DictionaryU5;
import com.technegames.dict.V.DictionaryV1;
import com.technegames.dict.V.DictionaryV2;
import com.technegames.dict.V.DictionaryV3;
import com.technegames.dict.V.DictionaryV4;
import com.technegames.dict.V.DictionaryV5;
import com.technegames.dict.W.DictionaryW1;
import com.technegames.dict.W.DictionaryW2;
import com.technegames.dict.W.DictionaryW3;
import com.technegames.dict.W.DictionaryW4;
import com.technegames.dict.W.DictionaryW5;
import com.technegames.dict.X.DictionaryX2;
import com.technegames.dict.X.DictionaryX3;
import com.technegames.dict.X.DictionaryX4;
import com.technegames.dict.X.DictionaryX5;
import com.technegames.dict.Y.DictionaryY1;
import com.technegames.dict.Y.DictionaryY2;
import com.technegames.dict.Y.DictionaryY3;
import com.technegames.dict.Y.DictionaryY4;
import com.technegames.dict.Y.DictionaryY5;
import com.technegames.dict.Z.DictionaryZ1;
import com.technegames.dict.Z.DictionaryZ2;
import com.technegames.dict.Z.DictionaryZ3;
import com.technegames.dict.Z.DictionaryZ4;
import com.technegames.dict.Z.DictionaryZ5;
import com.technegames.framework.Music;
import com.technegames.framework.Pixmap;
import com.technegames.framework.Sound;

public class Assets {
	public static DictionaryA1 dictA1;
	public static DictionaryA2 dictA2;
	public static DictionaryA3 dictA3;
	public static DictionaryA4 dictA4;
	public static DictionaryA5 dictA5;
	public static DictionaryB1 dictB1;
	public static DictionaryB2 dictB2;
	public static DictionaryB3 dictB3;
	public static DictionaryB4 dictB4;
	public static DictionaryB5 dictB5;
	public static DictionaryC1 dictC1;
	public static DictionaryC2 dictC2;
	public static DictionaryC3 dictC3;
	public static DictionaryC4 dictC4;
	public static DictionaryC5 dictC5;
	public static DictionaryD1 dictD1;
	public static DictionaryD2 dictD2;
	public static DictionaryD3 dictD3;
	public static DictionaryD4 dictD4;
	public static DictionaryD5 dictD5;
	public static DictionaryE1 dictE1;
	public static DictionaryE2 dictE2;
	public static DictionaryE3 dictE3;
	public static DictionaryE4 dictE4;
	public static DictionaryE5 dictE5;
	public static DictionaryF1 dictF1;
	public static DictionaryF2 dictF2;
	public static DictionaryF3 dictF3;
	public static DictionaryF4 dictF4;
	public static DictionaryF5 dictF5;
	public static DictionaryG1 dictG1;
	public static DictionaryG2 dictG2;
	public static DictionaryG3 dictG3;
	public static DictionaryG4 dictG4;
	public static DictionaryG5 dictG5;
	public static DictionaryH1 dictH1;
	public static DictionaryH2 dictH2;
	public static DictionaryH3 dictH3;
	public static DictionaryH4 dictH4;
	public static DictionaryH5 dictH5;
	public static DictionaryI1 dictI1;
	public static DictionaryI2 dictI2;
	public static DictionaryI3 dictI3;
	public static DictionaryI4 dictI4;
	public static DictionaryI5 dictI5;
	public static DictionaryJ1 dictJ1;
	public static DictionaryJ2 dictJ2;
	public static DictionaryJ3 dictJ3;
	public static DictionaryJ4 dictJ4;
	public static DictionaryJ5 dictJ5;
	public static DictionaryK1 dictK1;
	public static DictionaryK2 dictK2;
	public static DictionaryK3 dictK3;
	public static DictionaryK4 dictK4;
	public static DictionaryK5 dictK5;
	public static DictionaryL1 dictL1;
	public static DictionaryL2 dictL2;
	public static DictionaryL3 dictL3;
	public static DictionaryL4 dictL4;
	public static DictionaryL5 dictL5;
	public static DictionaryM1 dictM1;
	public static DictionaryM2 dictM2;
	public static DictionaryM3 dictM3;
	public static DictionaryM4 dictM4;
	public static DictionaryM5 dictM5;
	public static DictionaryN1 dictN1;
	public static DictionaryN2 dictN2;
	public static DictionaryN3 dictN3;
	public static DictionaryN4 dictN4;
	public static DictionaryN5 dictN5;
	public static DictionaryO1 dictO1;
	public static DictionaryO2 dictO2;
	public static DictionaryO3 dictO3;
	public static DictionaryO4 dictO4;
	public static DictionaryO5 dictO5;
	public static DictionaryP1 dictP1;
	public static DictionaryP2 dictP2;
	public static DictionaryP3 dictP3;
	public static DictionaryP4 dictP4;
	public static DictionaryP5 dictP5;
	public static DictionaryQ1 dictQ1;
	public static DictionaryQ5 dictQ5;
	public static DictionaryR1 dictR1;
	public static DictionaryR2 dictR2;
	public static DictionaryR3 dictR3;
	public static DictionaryR4 dictR4;
	public static DictionaryR5 dictR5;
	public static DictionaryS1 dictS1;
	public static DictionaryS2 dictS2;
	public static DictionaryS3 dictS3;
	public static DictionaryS4 dictS4;
	public static DictionaryS5 dictS5;
	public static DictionaryT1 dictT1;
	public static DictionaryT2 dictT2;
	public static DictionaryT3 dictT3;
	public static DictionaryT4 dictT4;
	public static DictionaryT5 dictT5;
	public static DictionaryU1 dictU1;
	public static DictionaryU2 dictU2;
	public static DictionaryU3 dictU3;
	public static DictionaryU4 dictU4;
	public static DictionaryU5 dictU5;
	public static DictionaryV1 dictV1;
	public static DictionaryV2 dictV2;
	public static DictionaryV3 dictV3;
	public static DictionaryV4 dictV4;
	public static DictionaryV5 dictV5;
	public static DictionaryW1 dictW1;
	public static DictionaryW2 dictW2;
	public static DictionaryW3 dictW3;
	public static DictionaryW4 dictW4;
	public static DictionaryW5 dictW5;
	public static DictionaryX2 dictX2;
	public static DictionaryX3 dictX3;
	public static DictionaryX4 dictX4;
	public static DictionaryX5 dictX5;
	public static DictionaryY1 dictY1;
	public static DictionaryY2 dictY2;
	public static DictionaryY3 dictY3;
	public static DictionaryY4 dictY4;
	public static DictionaryY5 dictY5;
	public static DictionaryZ1 dictZ1;
	public static DictionaryZ2 dictZ2;
	public static DictionaryZ3 dictZ3;
	public static DictionaryZ4 dictZ4;
	public static DictionaryZ5 dictZ5;
	
	//Tools
	public static DictionaryLoader dict;
	public static UsedWords usedWords;
	
	//Graphics
	public static Pixmap stats;
	public static Pixmap bg;
	public static Pixmap head;
	public static Pixmap item1;
	public static Pixmap item2;
	public static Pixmap item3;
	public static Pixmap newhs;
	public static Pixmap go;
	public static Pixmap options;
	public static Pixmap submit;
	public static Pixmap delete;
	
	//Music
	public static Music bgm;
	public static Music intro;
	
	//Sounds
	public static Sound click;
	public static Sound eat;
	public static Sound boom;
	public static Sound death;
}
